/* Calculate templet total for UICs and LDUICs */
SELECT A.UIC, A.LDUIC, SUM(A.AUTHMIL) AS AUTHS, ROUND(0.15 * SUM(A.AUTHMIL)) AS TEMPLETS
FROM AC_UIC_FY20 AS A
WHERE A.AUTHMIL > 0
GROUP BY A.UIC, A.LDUIC;

/* Calculate templet total for AA UICs */
SELECT 
	A.UIC, 
	SUM(A.AUTHMIL) AS AUTHS, 
	ROUND(0.15 * SUM(A.AUTHMIL)) AS TEMPLETS
FROM 
	AC_UIC_FY20 AS A
WHERE 
	A.AUTHMIL > 0
GROUP BY 
	A.UIC;

/* Find all HDUICs in DRRS-A Extract */
SELECT A.UIC, A.ANAME
FROM DRRSA_UIC AS A
WHERE RIGHT(A.UIC, 2) = 'HD';

/* Find all AA UICs that have an HD UIC */
SELECT 
	A.UIC, 
	A.ANAME,
	A.COMPO
FROM 
	DRRSA_UIC AS A
WHERE 
	RIGHT(A.UIC, 2) = 'AA' 
	OR RIGHT(A.UIC, 2) = 'HD'
	AND A.COMPO = '1';
	
/* Find all UICs that have a last character of D */
SELECT	
	A.UIC,
	A.ANAME,
	A.COMPO
FROM
	DRRSA_UIC AS A
WHERE
	RIGHT(A.UIC, 1) = 'D'
	AND A.COMPO = '1';

/* Find all distinct compo 1 UICs in the DRRS-A extract */
SELECT DISTINCT A.UIC
FROM 
	DRRSA_UIC AS A
WHERE 
	RIGHT(A.UIC, 2) = 'AA'
	AND A.COMPO = '1';

/* Find all distinct compo 1 UICs in the AOS extract */
SELECT 
	DISTINCT A.UIC
FROM 
	AC_UIC_FY20 AS A
WHERE 
	RIGHT(A.UIC, 2) = 'AA'
	AND A.COMPO = '1';
	
/* Join UICs on HDUICs and calculate templets*/
SELECT
	F.UIC, 
	D.UIC AS HDUIC,
	F.AUTHS,
	F.TEMPLETS
FROM
(
	SELECT 
		F_A.UIC, 
		SUM(F_A.AUTHMIL) AS AUTHS, 
		ROUND(0.15 * SUM(F_A.AUTHMIL)) AS TEMPLETS
	FROM 
		AC_UIC_FY20 AS F_A
	WHERE 
		F_A.AUTHMIL > 0
		AND RIGHT(F_A.UIC, 2) <> '99'
	GROUP BY 
		F_A.UIC
) AS F,
(
	SELECT 
		D_A.UIC, 
		D_A.ANAME
	FROM 
		DRRSA_UIC AS D_A
	WHERE 
		RIGHT(D_A.UIC, 2) = 'HD'
) AS D
WHERE
	LEFT(F.UIC, 4) = LEFT(D.UIC, 4)
	
/* Join UICs on HDUICs and calculate templets with JOIN operator*/
SELECT
	F.UIC, 
	D.UIC AS HDUIC,
	F.AUTHS,
	F.TEMPLETS
FROM
(
	SELECT 
		F_A.UIC,
		LEFT(F_A.UIC, 4) AS UICSHORT,
		SUM(F_A.AUTHMIL) AS AUTHS, 
		ROUND(0.15 * SUM(F_A.AUTHMIL)) AS TEMPLETS
	FROM 
		AC_UIC_FY20 AS F_A
	WHERE 
		F_A.AUTHMIL > 0
		AND RIGHT(F_A.UIC, 2) <> '99'
	GROUP BY 
		F_A.UIC
) AS F
LEFT JOIN
(
	SELECT 
		D_A.UIC,
		LEFT(D_A.UIC, 4) AS UICSHORT,
		D_A.ANAME
	FROM 
		DRRSA_UIC AS D_A
	WHERE 
		RIGHT(D_A.UIC, 2) = 'HD'
) AS D
ON
	F.UICSHORT = D.UICSHORT

	
/* Join UICs on HDUICs and sum auths*/
SELECT
	F.UIC, 
	D.UIC AS HDUIC,
	F.AUTHS
FROM
(
	SELECT 
		F_A.UIC, 
		SUM(F_A.AUTHMIL) AS AUTHS
	FROM 
		AC_UIC_FY20 AS F_A
	WHERE 
		F_A.AUTHMIL > 0
		AND RIGHT(F_A.UIC, 2) <> '99'
	GROUP BY 
		F_A.UIC
) AS F,
(
	SELECT 
		D_A.UIC, 
		D_A.ANAME
	FROM 
		DRRSA_UIC AS D_A
	WHERE 
		RIGHT(D_A.UIC, 2) = 'HD'
) AS D
WHERE
	LEFT(F.UIC, 4) = LEFT(D.UIC, 4)
	

	/* Join pre calculated UIC templets on DRRS-A HDUICs */
SELECT
	F.UIC, 
	D.UIC AS HDUIC,
	F.AUTHS,
	F.TEMPLETS
FROM
	FMS_UIC_TEMPLETS AS F
LEFT JOIN
(
	SELECT 
		D_A.UIC,
		LEFT(D_A.UIC, 4) AS UICSHORT,
		D_A.ANAME
	FROM 
		DRRSA_UIC AS D_A
	WHERE 
		RIGHT(D_A.UIC, 2) = 'HD'
) AS D
ON
	F.UICSHORT = D.UICSHORT

/* Find all primary sub-code UICs for COMPO 1 */
SELECT 
	D.UIC,
	D.ANAME,
	D.COMPO
FROM
	DRRSA_UIC AS D
WHERE
	RIGHT(D.UIC, 2) = 'A0' OR
	RIGHT(D.UIC, 2) = 'B0' OR
	RIGHT(D.UIC, 2) = 'C0' OR
	RIGHT(D.UIC, 2) = 'E0' OR
	RIGHT(D.UIC, 2) = 'F0' OR
	RIGHT(D.UIC, 2) = 'G0' OR
	RIGHT(D.UIC, 2) = 'T0';

/* Find all primary sub-code DUICs for COMPO 1 */
SELECT 
	D.UIC,
	D.ANAME,
	D.COMPO
FROM
	DRRSA_UIC AS D
WHERE
	RIGHT(D.UIC, 2) = 'AD' OR
	RIGHT(D.UIC, 2) = 'BD' OR
	RIGHT(D.UIC, 2) = 'CD' OR
	RIGHT(D.UIC, 2) = 'ED' OR
	RIGHT(D.UIC, 2) = 'FD' OR
	RIGHT(D.UIC, 2) = 'GD' OR
	RIGHT(D.UIC, 2) = 'TD';
	

SELECT 
	UIC.UIC,
	DUIC.UIC AS DUIC,
	UIC.ANAME,
	UIC.COMPO
FROM
(
	SELECT
		D.UIC,
		D.ANAME,
		D.COMPO,
		LEFT(D.UIC, 5) AS SHORT_UIC
	FROM DRRSA_UIC AS D
	WHERE
		RIGHT(D.UIC, 2) = 'A0' OR
		RIGHT(D.UIC, 2) = 'B0' OR
		RIGHT(D.UIC, 2) = 'C0' OR
		RIGHT(D.UIC, 2) = 'E0' OR
		RIGHT(D.UIC, 2) = 'F0' OR
		RIGHT(D.UIC, 2) = 'G0' OR
		RIGHT(D.UIC, 2) = 'T0'
) AS UIC
LEFT JOIN
(
	SELECT 
		D.UIC,
		D.ANAME,
		D.COMPO,
		LEFT(D.UIC, 5) AS SHORT_UIC
	FROM
		DRRSA_UIC AS D
	WHERE
		RIGHT(D.UIC, 2) = 'AD' OR
		RIGHT(D.UIC, 2) = 'BD' OR
		RIGHT(D.UIC, 2) = 'CD' OR
		RIGHT(D.UIC, 2) = 'ED' OR
		RIGHT(D.UIC, 2) = 'FD' OR
		RIGHT(D.UIC, 2) = 'GD' OR
		RIGHT(D.UIC, 2) = 'TD'
) AS DUIC
ON
	UIC.SHORT_UIC = DUIC.SHORT_UIC;
	
	
SELECT 
	ST.STACO, 
	DRRSA_UIC.HOGEO, 
	ST.UIC, 
	ST.LOCATION AS FMSLOC, 
	ST.CITY AS FMSCITY, 
	ST.STATE AS FMSSTATE, 
	ST.CNTRY AS FMSCNTRY, 
	DRRSA_UIC.GEOLOCATION_NAME AS DRRSLOC,
	DRRSA_UIC.ADDRESS_CITY AS DRRSCITY,
	DRRSA_UIC.ST_ABBRN AS DRRSSTATE,
	DRRSA_UIC.CNTRY_CD AS DRRSCNTRY
FROM FC_STACO AS ST
LEFT JOIN DRRSA_UIC
ON ST.UIC = DRRSA_UIC.UIC;
	
	
	
	
	
	
	
	
	
	
	
	
	
	